### ISSUE TITLE
Provide an upgraded 3.2 branch that works with 3.2.x

### ISSUE THREAD

**Issue by jexp** [neo4j-contrib/neo4j-graph-algorithms#193]
New Branch (broken) https://github.com/neo4j-contrib/neo4j-graph-algorithms/tree/3.2

There are a bunch of compile errors due to Kernel API changes.

These methods were changed away from Cursors

* nodeCursorGetAll
* nodeCursorGetForLabel
* relationshipCursorGetAll
* NodeItem and RelationshipItem changed

```
[ERROR] /Users/mh/d/java/neo/neo4j-graph-algorithms/core/src/main/java/org/neo4j/graphalgo/core/utils/Importer.java:[260,23] cannot find symbol
[ERROR] symbol:   method nodeCursorGetAll()
[ERROR] location: variable readOp of type org.neo4j.kernel.api.ReadOperations
[ERROR] /Users/mh/d/java/neo/neo4j-graph-algorithms/core/src/main/java/org/neo4j/graphalgo/core/utils/Importer.java:[262,23] cannot find symbol
[ERROR] symbol:   method nodeCursorGetForLabel(int)
[ERROR] location: variable readOp of type org.neo4j.kernel.api.ReadOperations
[ERROR] /Users/mh/d/java/neo/neo4j-graph-algorithms/core/src/main/java/org/neo4j/graphalgo/core/sources/BufferedAllRelationshipIterator.java:[117,23] cannot find symbol
[ERROR] symbol:   method relationshipCursorGetAll()
[ERROR] location: variable readOp of type org.neo4j.kernel.api.ReadOperations
[ERROR] /Users/mh/d/java/neo/neo4j-graph-algorithms/core/src/main/java/org/neo4j/graphalgo/core/leightweight/LightGraphFactory.java:[83,29] cannot find symbol
[ERROR] symbol:   method nodeCursorGetAll()
[ERROR] location: variable readOp of type org.neo4j.kernel.api.ReadOperations
[ERROR] /Users/mh/d/java/neo/neo4j-graph-algorithms/core/src/main/java/org/neo4j/graphalgo/core/leightweight/LightGraphFactory.java:[84,29] cannot find symbol
[ERROR] symbol:   method nodeCursorGetForLabel(int)
[ERROR] location: variable readOp of type org.neo4j.kernel.api.ReadOperations
[ERROR] /Users/mh/d/java/neo/neo4j-graph-algorithms/core/src/main/java/org/neo4j/graphalgo/core/leightweight/LightGraphFactory.java:[128,23] cannot find symbol
[ERROR] symbol:   method relationships(org.neo4j.storageengine.api.Direction)
[ERROR] location: variable node of type org.neo4j.storageengine.api.NodeItem
[ERROR] /Users/mh/d/java/neo/neo4j-graph-algorithms/core/src/main/java/org/neo4j/graphalgo/core/leightweight/LightGraphFactory.java:[129,23] cannot find symbol
[ERROR] symbol:   method relationships(org.neo4j.storageengine.api.Direction,int[])
[ERROR] location: variable node of type org.neo4j.storageengine.api.NodeItem
[ERROR] /Users/mh/d/java/neo/neo4j-graph-algorithms/core/src/main/java/org/neo4j/graphalgo/core/leightweight/LightGraphFactory.java:[140,56] cannot find symbol
[ERROR] symbol:   method property(int)
[ERROR] location: variable rel of type org.neo4j.storageengine.api.RelationshipItem
[ERROR] /Users/mh/d/java/neo/neo4j-graph-algorithms/core/src/main/java/org/neo4j/graphalgo/core/utils/container/RelationshipContainer.java:[197,45] cannot find symbol
[ERROR] symbol:   method degree(org.neo4j.storageengine.api.Direction)
[ERROR] location: variable nodeItem of type org.neo4j.storageengine.api.NodeItem
[ERROR] /Users/mh/d/java/neo/neo4j-graph-algorithms/core/src/main/java/org/neo4j/graphalgo/core/utils/container/RelationshipContainer.java:[199,45] cannot find symbol
[ERROR] symbol:   method degree(org.neo4j.storageengine.api.Direction,int)
[ERROR] location: variable nodeItem of type org.neo4j.storageengine.api.NodeItem
[ERROR] /Users/mh/d/java/neo/neo4j-graph-algorithms/core/src/main/java/org/neo4j/graphalgo/core/utils/container/RelationshipContainer.java:[201,21] cannot find symbol
[ERROR] symbol:   method relationships(org.neo4j.storageengine.api.Direction,int[])
[ERROR] location: variable nodeItem of type org.neo4j.storageengine.api.NodeItem
[ERROR] /Users/mh/d/java/neo/neo4j-graph-algorithms/core/src/main/java/org/neo4j/graphalgo/core/neo4jview/WeightedRelationIteratorImpl.java:[48,82] incompatible types: int cannot be converted to int[]
[ERROR] /Users/mh/d/java/neo/neo4j-graph-algorithms/core/src/main/java/org/neo4j/graphalgo/core/neo4jview/WeightedRelationIteratorImpl.java:[68,56] cannot find symbol
[ERROR] symbol:   method relationshipCursor(long)
[ERROR] location: variable read of type org.neo4j.kernel.api.ReadOperations
[ERROR] /Users/mh/d/java/neo/neo4j-graph-algorithms/core/src/main/java/org/neo4j/graphalgo/core/neo4jview/WeightedRelationIteratorImpl.java:[73,57] cannot find symbol
[ERROR] symbol:   method property(int)
[ERROR] location: variable item of type org.neo4j.storageengine.api.RelationshipItem
[ERROR] /Users/mh/d/java/neo/neo4j-graph-algorithms/core/src/main/java/org/neo4j/graphalgo/core/sources/SingleRunAllRelationIterator.java:[35,27] cannot find symbol
[ERROR] symbol:   method relationshipCursorGetAll()
[ERROR] location: variable readOperations of type org.neo4j.kernel.api.ReadOperations
[ERROR] /Users/mh/d/java/neo/neo4j-graph-algorithms/core/src/main/java/org/neo4j/graphalgo/core/neo4jview/GraphView.java:[61,56] cannot find symbol
[ERROR] symbol:   method nodeCursor(long)
[ERROR] location: variable read of type org.neo4j.kernel.api.ReadOperations
[ERROR] /Users/mh/d/java/neo/neo4j-graph-algorithms/core/src/main/java/org/neo4j/graphalgo/core/neo4jview/GraphView.java:[63,75] cannot find symbol
[ERROR] symbol:   method relationships(org.neo4j.storageengine.api.Direction,int)
[ERROR] location: variable nodeItem of type org.neo4j.storageengine.api.NodeItem
[ERROR] /Users/mh/d/java/neo/neo4j-graph-algorithms/core/src/main/java/org/neo4j/graphalgo/core/neo4jview/GraphView.java:[79,108] incompatible types: int cannot be converted to int[]
[ERROR] /Users/mh/d/java/neo/neo4j-graph-algorithms/core/src/main/java/org/neo4j/graphalgo/core/neo4jview/GraphView.java:[82,81] cannot find symbol
[ERROR] symbol:   method relationshipCursor(long)
[ERROR] location: variable read of type org.neo4j.kernel.api.ReadOperations
[ERROR] /Users/mh/d/java/neo/neo4j-graph-algorithms/core/src/main/java/org/neo4j/graphalgo/core/neo4jview/GraphView.java:[118,60] cannot find symbol
[ERROR] symbol:   method nodeCursorGetAll()
[ERROR] location: variable read of type org.neo4j.kernel.api.ReadOperations
[ERROR] /Users/mh/d/java/neo/neo4j-graph-algorithms/core/src/main/java/org/neo4j/graphalgo/core/neo4jview/GraphView.java:[126,60] cannot find symbol
[ERROR] symbol:   method nodeCursorGetForLabel(int)
[ERROR] location: variable read of type org.neo4j.kernel.api.ReadOperations
[ERROR] /Users/mh/d/java/neo/neo4j-graph-algorithms/core/src/main/java/org/neo4j/graphalgo/core/utils/WeightedRelationshipContainer.java:[214,21] cannot find symbol
[ERROR] symbol:   method nodeCursorGetAll()
[ERROR] location: variable read of type org.neo4j.kernel.api.ReadOperations
[ERROR] /Users/mh/d/java/neo/neo4j-graph-algorithms/core/src/main/java/org/neo4j/graphalgo/core/utils/WeightedRelationshipContainer.java:[226,45] cannot find symbol
[ERROR] symbol:   method degree(org.neo4j.storageengine.api.Direction)
[ERROR] location: variable nodeItem of type org.neo4j.storageengine.api.NodeItem
[ERROR] /Users/mh/d/java/neo/neo4j-graph-algorithms/core/src/main/java/org/neo4j/graphalgo/core/utils/WeightedRelationshipContainer.java:[228,45] cannot find symbol
[ERROR] symbol:   method degree(org.neo4j.storageengine.api.Direction,int)
[ERROR] location: variable nodeItem of type org.neo4j.storageengine.api.NodeItem
[ERROR] /Users/mh/d/java/neo/neo4j-graph-algorithms/core/src/main/java/org/neo4j/graphalgo/core/utils/WeightedRelationshipContainer.java:[230,21] cannot find symbol
[ERROR] symbol:   method relationships(org.neo4j.storageengine.api.Direction,int[])
[ERROR] location: variable nodeItem of type org.neo4j.storageengine.api.NodeItem
[ERROR] /Users/mh/d/java/neo/neo4j-graph-algorithms/core/src/main/java/org/neo4j/graphalgo/core/heavyweight/HeavyGraphFactory.java:[156,29] cannot find symbol
[ERROR] symbol:   method degree(org.neo4j.storageengine.api.Direction)
[ERROR] location: variable node of type org.neo4j.storageengine.api.NodeItem
[ERROR] /Users/mh/d/java/neo/neo4j-graph-algorithms/core/src/main/java/org/neo4j/graphalgo/core/heavyweight/HeavyGraphFactory.java:[157,28] cannot find symbol
[ERROR] symbol:   method degree(org.neo4j.storageengine.api.Direction)
[ERROR] location: variable node of type org.neo4j.storageengine.api.NodeItem
[ERROR] /Users/mh/d/java/neo/neo4j-graph-algorithms/core/src/main/java/org/neo4j/graphalgo/core/heavyweight/HeavyGraphFactory.java:[158,29] cannot find symbol
[ERROR] symbol:   method relationships(org.neo4j.storageengine.api.Direction)
[ERROR] location: variable node of type org.neo4j.storageengine.api.NodeItem
[ERROR] /Users/mh/d/java/neo/neo4j-graph-algorithms/core/src/main/java/org/neo4j/graphalgo/core/heavyweight/HeavyGraphFactory.java:[159,28] cannot find symbol
[ERROR] symbol:   method relationships(org.neo4j.storageengine.api.Direction)
[ERROR] location: variable node of type org.neo4j.storageengine.api.NodeItem
[ERROR] /Users/mh/d/java/neo/neo4j-graph-algorithms/core/src/main/java/org/neo4j/graphalgo/core/heavyweight/HeavyGraphFactory.java:[161,29] cannot find symbol
[ERROR] symbol:   method degree(org.neo4j.storageengine.api.Direction,int)
[ERROR] location: variable node of type org.neo4j.storageengine.api.NodeItem
[ERROR] /Users/mh/d/java/neo/neo4j-graph-algorithms/core/src/main/java/org/neo4j/graphalgo/core/heavyweight/HeavyGraphFactory.java:[162,28] cannot find symbol
[ERROR] symbol:   method degree(org.neo4j.storageengine.api.Direction,int)
[ERROR] location: variable node of type org.neo4j.storageengine.api.NodeItem
[ERROR] /Users/mh/d/java/neo/neo4j-graph-algorithms/core/src/main/java/org/neo4j/graphalgo/core/heavyweight/HeavyGraphFactory.java:[163,29] cannot find symbol
[ERROR] symbol:   method relationships(org.neo4j.storageengine.api.Direction,int[])
[ERROR] location: variable node of type org.neo4j.storageengine.api.NodeItem
[ERROR] /Users/mh/d/java/neo/neo4j-graph-algorithms/core/src/main/java/org/neo4j/graphalgo/core/heavyweight/HeavyGraphFactory.java:[164,28] cannot find symbol
[ERROR] symbol:   method relationships(org.neo4j.storageengine.api.Direction,int[])
[ERROR] location: variable node of type org.neo4j.storageengine.api.NodeItem
[ERROR] /Users/mh/d/java/neo/neo4j-graph-algorithms/core/src/main/java/org/neo4j/graphalgo/core/heavyweight/HeavyGraphFactory.java:[166,49] cannot find symbol
[ERROR] symbol:   method property(int)
[ERROR] location: variable node of type org.neo4j.storageengine.api.NodeItem
[ERROR] /Users/mh/d/java/neo/neo4j-graph-algorithms/core/src/main/java/org/neo4j/graphalgo/core/heavyweight/HeavyGraphFactory.java:[171,47] cannot find symbol
[ERROR] symbol:   method property(int)
[ERROR] location: variable node of type org.neo4j.storageengine.api.NodeItem
[ERROR] /Users/mh/d/java/neo/neo4j-graph-algorithms/core/src/main/java/org/neo4j/graphalgo/core/heavyweight/HeavyGraphFactory.java:[188,56] cannot find symbol
[ERROR] symbol:   method property(int)
[ERROR] location: variable rel of type org.neo4j.storageengine.api.RelationshipItem
[ERROR] /Users/mh/d/java/neo/neo4j-graph-algorithms/core/src/main/java/org/neo4j/graphalgo/core/heavyweight/HeavyGraphFactory.java:[255,54] cannot find symbol
[ERROR] symbol:   method nodeCursor(long)
[ERROR] location: variable readOp of type org.neo4j.kernel.api.ReadOperations
[ERROR] /Users/mh/d/java/neo/neo4j-graph-algorithms/core/src/main/java/org/neo4j/graphalgo/core/sources/BufferedWeightMap.java:[108,44] cannot find symbol
[ERROR] symbol:   method nodeCursorGetAll()
[ERROR] location: variable readOp of type org.neo4j.kernel.api.ReadOperations
[ERROR] /Users/mh/d/java/neo/neo4j-graph-algorithms/core/src/main/java/org/neo4j/graphalgo/core/sources/BufferedWeightMap.java:[110,44] cannot find symbol
[ERROR] symbol:   method nodeCursorGetForLabel(int)
[ERROR] location: variable readOp of type org.neo4j.kernel.api.ReadOperations
[ERROR] /Users/mh/d/java/neo/neo4j-graph-algorithms/core/src/main/java/org/neo4j/graphalgo/core/sources/BufferedWeightMap.java:[114,25] cannot find symbol
[ERROR] symbol:   method relationships(org.neo4j.storageengine.api.Direction,int[])
[ERROR] location: variable node of type org.neo4j.storageengine.api.NodeItem
[ERROR] /Users/mh/d/java/neo/neo4j-graph-algorithms/core/src/main/java/org/neo4j/graphalgo/core/neo4jview/RelationIteratorImpl.java:[43,77] incompatible types: int cannot be converted to int[]
[ERROR] /Users/mh/d/java/neo/neo4j-graph-algorithms/core/src/main/java/org/neo4j/graphalgo/core/neo4jview/RelationIteratorImpl.java:[62,56] cannot find symbol
[ERROR] symbol:   method relationshipCursor(long)
```

**Comment by jexp** [comment]
I looked at the code changes and not sure what's the best way of handling them.
We can either

1. determine what the migration path is for each idiom / construct and apply it in all the places
2. reproduce the previous API with the richer NodeItem / RelItem (by wrapping a ReadOperations + handling errors + cursors) in a flyweight object, so we could provide our own API in a single place so we can handle future Kernel API changes in a single place

While 1. might be more efficient, it might also be more brittle for the next kernel versions (dot versions) and 3.3

**Comment by jexp** [comment]
I implemented now a "Kernel" wrapper that restores the old behavior (mostly).

But we should really move to something more stable, probably proactively using the 3.3 cursor API

**Comment by jexp** [comment]
https://github.com/neo4j-contrib/neo4j-graph-algorithms/commit/f36799b6fa6f47e2c77adfcf1c336e3d3c9aeaa1
