### ISSUE TITLE
Algo procedures fail with NoSuchMethodError

### ISSUE THREAD

**Issue by antoniomaccioni** [neo4j-contrib/neo4j-graph-algorithms#410]
Sorry to bother, but I have issues running the plugin v3.2.2.1 taken from the official releases on an instance of Neo4j CE v3.2.3 deployed via docker. I was able to use the plugin on a local instance not installed with docker.

I get several  ```java.lang.NoSuchMethodError``` whenever I call a stored procedure.
For instance, with query:
> MATCH (start:Label{node_id: 'df7f0099-853f-41be-aee6-cb8b00c57821'}), (end:Label{node_id:'751cc519-53a4-4564-a1af-875a4078b5e8'})
CALL algo.shortestPath(start, end, 'strength', {write:false})
YIELD writeMillis,loadMillis,nodeCount, totalCost
RETURN writeMillis,loadMillis,nodeCount,totalCost

I get:
```
Neo.ClientError.Procedure.ProcedureCallFailed
Failed to invoke procedure `algo.shortestPath`: Caused by: java.lang.NoSuchMethodError: org.neo4j.helpers.Exceptions.chain(Ljava/lang/Throwable;Ljava/lang/Throwable;)Ljava/lang/Throwable;
```

With query (or with closeness centrality): 

> CALL algo.betweenness('Label', 'Edge', 
{write:true, writeProperty:'betweennessCentrality'}) 
 YIELD nodes, minCentrality, maxCentrality, sumCentrality, loadMillis, computeMillis, writeMillis

I get: 
```
Neo.ClientError.Procedure.ProcedureCallFailed
Failed to invoke procedure `algo.betweenness`: Caused by: java.lang.NoSuchMethodError: org.neo4j.kernel.api.ReadOperations.nodeCursorById(J)Lorg/neo4j/cursor/Cursor;
```

The plugin is correctly configured with

> dbms.security.procedures.unrestricted=algo.*,apoc.*

I get the list of `algo` stored procedures with `CALL dbms.procedures()`. Also `APOC` plugin is working fine.

**Comment by tomasonjo** [comment]
Do you use the latest build or do you use official release ?

**Comment by antoniomaccioni** [comment]
Official release. Plugin v3.2.2.1 on Neo4j v3.2.3 community edition.

**Comment by knutwalker** [comment]
The missing method was added in https://github.com/neo4j/neo4j/commit/c3f1ef34863fa7de98bb6dfb4dc62661d483073d as early as 3.1.0-rc1 and hasn't been changed since. If the runtime cannot find it, it sounds like there is a pre 3.1.0 version of Neo4j loaded somewhere on the classpath. If you could run the plugin locally, that points to the Docker deployment, which might load outdated jar files (?).
Similar with the second method, only it was [introduced in 3.2.0-alpha02](https://github.com/neo4j/neo4j/commit/652ebb67326843b09660e39a503eee856b0ce5be#diff-8f548b0aae7189a5c4e5df1ae0781c50).

**Comment by antoniomaccioni** [comment]
This is what it sounds, but I am running on v3.2.3 and there is no other Neo4j loaded on the classpath.

**Comment by mneedham** [comment]
@antoniomaccioni did you manage to make any progress on this?

**Comment by antoniomaccioni** [comment]
I did not progress on this. 
But the problem disappeared when I migrated to v3.3.1
